### ISSUE TITLE
Doesn't work with multi-root workspaces

### ISSUE THREAD

**Issue by notpushkin** [jkillian/vscode-custom-local-formatters#2]
First of all, thank you for your great work! I'm using this extension to format Python code in accordance with [wemake-python-styleguide](https://wemake-python-stylegui.de) (which is tricky to get right with existing autoformatting extensions alone) literally every day.

I'm currently wotking on a tightly coupled set of projects, which I manage as a [multi-root workspace](https://code.visualstudio.com/docs/editor/multi-root-workspaces). For some of them, I want to use this extension to autoformat code. However, when I open `.vscode/settings.json`, I get the following error for the `customLocalFormatters.formatters` property:

> This setting cannot be applied in this workspace. It will be applied when you open the containing workspace folder directly.

And when I try to run Format Document, I get the following error:

> Extension 'Custom Local Formatters' cannot format 'foldername - filename'

I suppose this extension doesn't play well with multi-root workspaces. Is there any way to fix that? :)

UPD: seems like [Adopting Multi Root Workspace APIs](https://github.com/microsoft/vscode/wiki/Adopting-Multi-Root-Workspace-APIs) might be relevant here. I'll try to work out a PR tonight or maybe later this week.

**Comment by notpushkin** [comment]
Turns out settings work when applied in the `.code-workspace` directly:

```js
{
  "folders": [...],
  "settings": {
    "customLocalFormatters.formatters": [
      {
        "command": "poetry run isort - | poetry run autopep8 - | poetry run add-trailing-comma --exit-zero-even-if-changed -",
        "languages": ["python"]
      }
    ]
  }
}
```

Perhaps worth mentioning in the docs? Apart from that I think this covers most of the use cases, considering that code style is likely to be the same across a given workspace.

**Comment by jkillian** [comment]
Hi @notpushkin! Sorry for only responding nine months later... but would be happy to have a note added in the README about this - feel free to drop a PR and I'd be happy to merge it!
